import "dotenv/config";
import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaLibSql } from "@prisma/adapter-libsql";

const adapter = new PrismaLibSql({
  url: process.env.DATABASE_URL ?? "file:./dev.db",
  authToken: process.env.DATABASE_AUTH_TOKEN,
});
const prisma = new PrismaClient({ adapter });

const recipes = [
  ["ratatouille-001", "Ratatouille ensoleillée", "Un plat généreux de légumes mijotés.", ["2 courgettes", "1 aubergine", "4 tomates", "Huile d'olive"], ["Couper les légumes.", "Faire revenir l'oignon.", "Ajouter les légumes et mijoter 35 minutes."], ["végétarien", "famille"], 15, 30, 4],
  ["tarte-pommes-001", "Tarte aux pommes rustique", "Une tarte simple et réconfortante.", ["1 pâte brisée", "4 pommes", "1 cuillère de cannelle"], ["Préchauffer le four à 180 °C.", "Disposer les pommes sur la pâte.", "Cuire 40 minutes."], ["dessert"], 20, 40, 6],
  ["pates-citron-001", "Pâtes citron & ricotta", "Des pâtes fraîches et lumineuses pour un soir de semaine.", ["250 g de pâtes", "1 citron", "150 g de ricotta", "Basilic"], ["Cuire les pâtes.", "Mélanger la ricotta et le jus de citron.", "Ajouter les pâtes et le basilic."], ["rapide", "végétarien"], 10, 15, 2],
  ["curry-pois-chiches-001", "Curry de pois chiches", "Un curry doux, crémeux et parfumé.", ["400 g de pois chiches", "1 oignon", "400 ml de lait de coco", "Curry", "Riz"], ["Faire revenir l'oignon.", "Ajouter le curry et les pois chiches.", "Verser le lait de coco et mijoter 20 minutes.", "Servir avec le riz."], ["végétarien", "sans viande"], 10, 25, 4],
  ["lasagnes-legumes-001", "Lasagnes aux légumes", "Des lasagnes fondantes à préparer en famille.", ["Feuilles de lasagne", "2 courgettes", "500 ml de sauce tomate", "Béchamel", "100 g de fromage râpé"], ["Faire revenir les légumes.", "Alterner les couches de sauce, légumes et pâte.", "Couvrir de béchamel et de fromage.", "Cuire 35 minutes à 180 °C."], ["famille", "four"], 25, 35, 6],
  ["poulet-citron-001", "Poulet rôti au citron", "Un poulet parfumé, tendre et facile à partager.", ["4 cuisses de poulet", "2 citrons", "3 gousses d'ail", "Thym", "Huile d'olive"], ["Déposer le poulet dans un plat.", "Ajouter citron, ail et thym.", "Rôtir 45 minutes à 200 °C."], ["famille", "four"], 10, 45, 4],
  ["salade-lentilles-001", "Salade de lentilles, feta et herbes", "Une salade complète à préparer à l'avance.", ["250 g de lentilles", "100 g de feta", "1 carotte", "Persil", "Vinaigrette"], ["Cuire les lentilles.", "Couper la carotte et émietter la feta.", "Mélanger avec les herbes et la vinaigrette."], ["salade", "déjeuner"], 15, 25, 4],
  ["soupe-potimarron-001", "Velouté de potimarron", "Un velouté doux pour les soirées fraîches.", ["1 potimarron", "1 oignon", "750 ml de bouillon", "10 cl de crème"], ["Faire revenir l'oignon.", "Ajouter le potimarron et le bouillon.", "Cuire 25 minutes puis mixer.", "Ajouter la crème."], ["soupe", "automne"], 15, 25, 4],
  ["risotto-champignons-001", "Risotto aux champignons", "Un risotto crémeux et généreux.", ["300 g de riz arborio", "250 g de champignons", "1 l de bouillon", "50 g de parmesan"], ["Faire revenir les champignons.", "Ajouter le riz.", "Verser le bouillon progressivement.", "Terminer avec le parmesan."], ["végétarien", "italien"], 15, 30, 4],
  ["omelette-fines-herbes-001", "Omelette aux fines herbes", "Un repas rapide avec les ingrédients du placard.", ["6 œufs", "Ciboulette", "Persil", "20 g de beurre", "Sel et poivre"], ["Battre les œufs avec les herbes.", "Faire fondre le beurre.", "Cuire l'omelette et la plier."], ["rapide", "déjeuner"], 5, 8, 2],
  ["gratin-dauphinois-001", "Gratin dauphinois", "Des pommes de terre fondantes et crémeuses.", ["1 kg de pommes de terre", "50 cl de crème", "1 gousse d'ail", "Muscade"], ["Émincer les pommes de terre.", "Frotter le plat avec l'ail.", "Verser la crème et assaisonner.", "Cuire 1 heure à 160 °C."], ["accompagnement", "famille"], 20, 60, 6],
  ["banana-bread-001", "Banana bread", "Le gâteau parfait pour utiliser des bananes mûres.", ["3 bananes mûres", "2 œufs", "180 g de farine", "80 g de sucre", "1 sachet de levure"], ["Écraser les bananes.", "Ajouter les œufs et le sucre.", "Incorporer la farine et la levure.", "Cuire 45 minutes à 180 °C."], ["dessert", "goûter"], 15, 45, 8],
  ["clafoutis-cerises-001", "Clafoutis aux cerises", "Un dessert moelleux et fruité.", ["500 g de cerises", "3 œufs", "100 g de farine", "50 cl de lait", "80 g de sucre"], ["Répartir les cerises dans le plat.", "Mélanger les autres ingrédients.", "Verser sur les cerises.", "Cuire 40 minutes à 180 °C."], ["dessert", "fruits"], 15, 40, 6],
  ["cookies-chocolat-001", "Cookies aux pépites de chocolat", "Des cookies croustillants dehors et moelleux dedans.", ["120 g de beurre", "100 g de sucre", "1 œuf", "220 g de farine", "100 g de chocolat"], ["Mélanger le beurre et le sucre.", "Ajouter l'œuf puis la farine.", "Incorporer le chocolat.", "Former les cookies et cuire 12 minutes à 180 °C."], ["dessert", "goûter"], 15, 12, 12],
  ["pancakes-001", "Pancakes du dimanche", "Des pancakes moelleux pour un petit déjeuner gourmand.", ["250 g de farine", "2 œufs", "300 ml de lait", "1 sachet de levure", "30 g de beurre"], ["Mélanger les ingrédients secs.", "Ajouter les œufs et le lait.", "Cuire une louche de pâte par face."], ["petit-déjeuner", "rapide"], 10, 15, 8],
  ["quiche-poireaux-001", "Quiche aux poireaux", "Une quiche douce et fondante.", ["1 pâte brisée", "3 poireaux", "3 œufs", "20 cl de crème", "100 g de fromage"], ["Émincer et faire fondre les poireaux.", "Mélanger les œufs et la crème.", "Garnir la pâte et cuire 35 minutes à 180 °C."], ["déjeuner", "famille"], 20, 35, 6],
  ["cake-olives-001", "Cake aux olives et feta", "Un cake salé à partager à l'apéritif.", ["200 g de farine", "3 œufs", "100 g de feta", "100 g d'olives", "1 sachet de levure"], ["Mélanger farine, œufs et levure.", "Ajouter feta et olives.", "Cuire 40 minutes à 180 °C."], ["apéritif", "salé"], 15, 40, 8],
  ["salade-grecque-001", "Salade grecque", "Une salade fraîche aux accents méditerranéens.", ["Tomates", "Concombre", "Feta", "Olives", "Oignon rouge"], ["Couper les légumes.", "Ajouter la feta et les olives.", "Assaisonner et servir frais."], ["salade", "été"], 15, 0, 4],
  ["taboule-001", "Taboulé aux herbes", "Un taboulé frais et citronné.", ["200 g de semoule", "3 tomates", "Menthe", "Persil", "2 citrons"], ["Réhydrater la semoule.", "Ajouter les tomates et les herbes.", "Assaisonner au citron et réserver au frais."], ["salade", "été"], 20, 0, 4],
  ["dahl-lentilles-001", "Dahl de lentilles corail", "Un plat végétarien parfumé et réconfortant.", ["250 g de lentilles corail", "1 oignon", "400 ml de lait de coco", "Curry", "Tomates concassées"], ["Faire revenir l'oignon et le curry.", "Ajouter les lentilles et les tomates.", "Verser le lait de coco et cuire 20 minutes."], ["végétarien", "indien"], 10, 25, 4],
  ["chili-sin-carne-001", "Chili sin carne", "Un chili végétarien généreux.", ["Haricots rouges", "Maïs", "Tomates concassées", "Poivron", "Épices"], ["Faire revenir le poivron.", "Ajouter les haricots, le maïs et les tomates.", "Mijoter 25 minutes."], ["végétarien", "épicé"], 15, 25, 4],
  ["boeuf-carottes-001", "Bœuf carottes", "Un grand classique mijoté.", ["800 g de bœuf à mijoter", "6 carottes", "1 oignon", "Bouillon", "Thym"], ["Faire dorer la viande.", "Ajouter les carottes et le bouillon.", "Mijoter 2 heures à feu doux."], ["tradition", "mijoté"], 20, 120, 6],
  ["blanquette-veau-001", "Blanquette de veau", "Une blanquette crémeuse et familiale.", ["800 g de veau", "4 carottes", "Champignons", "Bouillon", "Crème"], ["Cuire le veau dans le bouillon.", "Ajouter les légumes.", "Lier la sauce avec la crème et servir."], ["tradition", "famille"], 30, 90, 6],
  ["saumon-four-001", "Saumon rôti au four", "Un saumon simple avec une sauce citronnée.", ["4 pavés de saumon", "1 citron", "Aneth", "Huile d'olive"], ["Déposer le saumon dans un plat.", "Ajouter citron et aneth.", "Cuire 15 minutes à 180 °C."], ["poisson", "rapide"], 10, 15, 4],
  ["cabillaud-tomate-001", "Cabillaud à la tomate", "Un plat léger et parfumé.", ["4 dos de cabillaud", "400 g de tomates", "1 oignon", "Ail", "Basilic"], ["Faire revenir l'oignon et l'ail.", "Ajouter les tomates.", "Déposer le cabillaud et cuire 15 minutes."], ["poisson", "léger"], 10, 25, 4],
  ["crevettes-curry-001", "Crevettes au curry", "Des crevettes rapides dans une sauce onctueuse.", ["500 g de crevettes", "400 ml de lait de coco", "Curry", "1 oignon", "Coriandre"], ["Faire revenir l'oignon et le curry.", "Ajouter le lait de coco.", "Cuire les crevettes 5 minutes et parsemer de coriandre."], ["poisson", "rapide"], 10, 15, 4],
  ["poulet-curry-001", "Poulet au curry", "Un curry familial facile à préparer.", ["600 g de poulet", "1 oignon", "400 ml de lait de coco", "Curry", "Riz"], ["Faire dorer le poulet.", "Ajouter l'oignon et le curry.", "Verser le lait de coco et mijoter 20 minutes."], ["famille", "indien"], 15, 25, 4],
  ["boulettes-tomate-001", "Boulettes de viande sauce tomate", "Des boulettes tendres dans une sauce maison.", ["500 g de viande hachée", "1 œuf", "Chapelure", "400 g de tomates", "Persil"], ["Former les boulettes.", "Les faire dorer.", "Ajouter la sauce tomate et mijoter 20 minutes."], ["famille", "italien"], 20, 30, 4],
  ["spaghetti-bolognaise-001", "Spaghetti bolognaise", "Le plat familial incontournable.", ["400 g de spaghetti", "400 g de viande hachée", "400 g de tomates", "1 carotte", "Parmesan"], ["Faire revenir les légumes.", "Ajouter la viande puis les tomates.", "Mijoter 30 minutes et servir avec les pâtes."], ["pâtes", "famille"], 15, 35, 4],
  ["pesto-genovese-001", "Pesto genovese", "Un pesto maison au basilic frais.", ["1 bouquet de basilic", "50 g de pignons", "50 g de parmesan", "1 gousse d'ail", "Huile d'olive"], ["Mixer le basilic, les pignons et l'ail.", "Ajouter le parmesan.", "Verser l'huile jusqu'à obtenir la texture souhaitée."], ["sauce", "italien"], 10, 0, 4],
  ["gnocchis-tomate-001", "Gnocchis à la sauce tomate", "Un dîner rapide et réconfortant.", ["500 g de gnocchis", "400 g de tomates", "Mozzarella", "Basilic"], ["Préparer la sauce tomate.", "Cuire les gnocchis.", "Mélanger et gratiner avec la mozzarella."], ["rapide", "italien"], 10, 20, 4],
  ["pizza-margherita-001", "Pizza margherita", "Une pizza maison simple et généreuse.", ["1 pâte à pizza", "Tomates concassées", "Mozzarella", "Basilic", "Huile d'olive"], ["Étaler la pâte.", "Ajouter tomate et mozzarella.", "Cuire 12 minutes au four très chaud et ajouter le basilic."], ["italien", "famille"], 20, 12, 2],
  ["pommes-terre-roties-001", "Pommes de terre rôties", "Un accompagnement croustillant et parfumé.", ["800 g de pommes de terre", "Huile d'olive", "Paprika", "Romarin"], ["Couper les pommes de terre.", "Mélanger avec huile et épices.", "Rôtir 40 minutes à 200 °C."], ["accompagnement", "four"], 10, 40, 4],
  ["courgettes-farcies-001", "Courgettes farcies", "Des courgettes garnies et gratinées.", ["4 courgettes", "300 g de viande hachée", "Tomates", "Oignon", "Fromage râpé"], ["Évider les courgettes.", "Préparer la farce.", "Garnir et cuire 40 minutes à 180 °C."], ["légumes", "four"], 25, 40, 4],
  ["houmous-001", "Houmous maison", "Une crème de pois chiches pour l'apéritif.", ["400 g de pois chiches", "Tahini", "1 citron", "1 gousse d'ail", "Huile d'olive"], ["Mixer les pois chiches avec le tahini.", "Ajouter citron et ail.", "Détendre avec un peu d'eau et servir."], ["apéritif", "végétarien"], 10, 0, 6],
  ["guacamole-001", "Guacamole frais", "Un guacamole citronné à partager.", ["3 avocats", "1 tomate", "1 citron vert", "Coriandre", "Oignon rouge"], ["Écraser les avocats.", "Ajouter tomate, oignon et coriandre.", "Assaisonner au citron vert."], ["apéritif", "sans cuisson"], 10, 0, 4],
  ["bruschetta-tomate-001", "Bruschetta tomates basilic", "Des tartines méditerranéennes minute.", ["4 tranches de pain", "3 tomates", "Basilic", "Ail", "Huile d'olive"], ["Faire griller le pain.", "Frotter avec l'ail.", "Ajouter les tomates et le basilic."], ["apéritif", "rapide"], 10, 5, 4],
  ["focaccia-001", "Focaccia au romarin", "Un pain moelleux à partager.", ["500 g de farine", "Levure", "Eau", "Huile d'olive", "Romarin"], ["Pétrir la pâte.", "Laisser lever.", "Former la focaccia et ajouter huile et romarin.", "Cuire 25 minutes à 220 °C."], ["boulangerie", "italien"], 25, 25, 8],
  ["pain-banane-chocolat-001", "Pain banane chocolat", "Une version gourmande du banana bread.", ["3 bananes", "2 œufs", "180 g de farine", "100 g de chocolat", "80 g de sucre"], ["Écraser les bananes.", "Mélanger tous les ingrédients.", "Ajouter le chocolat et cuire 45 minutes."], ["dessert", "goûter"], 15, 45, 8],
  ["moelleux-chocolat-001", "Moelleux au chocolat", "Un gâteau fondant au cœur tendre.", ["200 g de chocolat", "100 g de beurre", "4 œufs", "80 g de sucre", "50 g de farine"], ["Faire fondre chocolat et beurre.", "Ajouter œufs, sucre et farine.", "Cuire 12 minutes à 200 °C."], ["dessert", "chocolat"], 15, 12, 6],
  ["mousse-chocolat-001", "Mousse au chocolat", "Une mousse légère et intense.", ["200 g de chocolat", "6 œufs", "1 pincée de sel"], ["Faire fondre le chocolat.", "Séparer les œufs.", "Monter les blancs et incorporer délicatement.", "Réserver au frais 3 heures."], ["dessert", "chocolat"], 20, 0, 6],
  ["riz-au-lait-001", "Riz au lait vanillé", "Un dessert doux comme un souvenir d'enfance.", ["100 g de riz rond", "1 l de lait", "80 g de sucre", "1 gousse de vanille"], ["Chauffer le lait avec la vanille.", "Ajouter le riz.", "Cuire 40 minutes en remuant.", "Sucrer et laisser refroidir."], ["dessert", "tradition"], 5, 40, 6],
  ["crepes-001", "Crêpes fines", "Des crêpes souples pour le goûter.", ["250 g de farine", "3 œufs", "500 ml de lait", "30 g de beurre", "1 cuillère de sucre"], ["Mélanger farine et œufs.", "Ajouter le lait progressivement.", "Cuire les crêpes dans une poêle chaude."], ["dessert", "goûter"], 10, 20, 10],
  ["compote-pommes-001", "Compote de pommes", "Une compote maison sans complication.", ["6 pommes", "Un peu d'eau", "Cannelle"], ["Éplucher et couper les pommes.", "Cuire avec un fond d'eau 20 minutes.", "Mixer ou écraser selon la texture souhaitée."], ["dessert", "fruits"], 10, 20, 4],
  ["granola-maison-001", "Granola maison", "Un granola croustillant pour les petits déjeuners.", ["300 g de flocons d'avoine", "Miel", "Noix", "Graines", "Huile de coco"], ["Mélanger tous les ingrédients.", "Étaler sur une plaque.", "Cuire 25 minutes à 160 °C en remuant."], ["petit-déjeuner", "préparation"], 10, 25, 10],
  ["smoothie-banane-001", "Smoothie banane et fruits rouges", "Un smoothie rapide et fruité.", ["1 banane", "150 g de fruits rouges", "1 yaourt", "Un peu de lait"], ["Mettre tous les ingrédients dans le blender.", "Mixer jusqu'à obtenir une texture lisse.", "Servir immédiatement."], ["petit-déjeuner", "rapide"], 5, 0, 2],
  ["salade-fruits-001", "Salade de fruits frais", "Un dessert coloré et léger.", ["2 pommes", "2 kiwis", "2 oranges", "Fraises", "Menthe"], ["Éplucher et couper les fruits.", "Mélanger délicatement.", "Ajouter la menthe et servir frais."], ["dessert", "léger"], 15, 0, 4],
  ["soupe-oignon-001", "Soupe à l'oignon gratinée", "Une soupe généreuse pour les soirées d'hiver.", ["6 oignons", "1 l de bouillon", "Pain", "Fromage râpé"], ["Faire caraméliser les oignons.", "Ajouter le bouillon et cuire 30 minutes.", "Répartir dans des bols, couvrir de pain et fromage, puis gratiner."], ["soupe", "hiver"], 15, 45, 4],
  ["minestrone-001", "Minestrone de légumes", "Une soupe complète aux légumes et aux pâtes.", ["2 carottes", "1 courgette", "Haricots blancs", "Tomates", "Petites pâtes"], ["Faire revenir les légumes.", "Ajouter tomates et bouillon.", "Cuire 25 minutes puis ajouter les pâtes."], ["soupe", "italien"], 20, 35, 6],
  ["salade-pates-001", "Salade de pâtes méditerranéenne", "Une salade pratique pour les repas d'été.", ["300 g de pâtes", "Tomates cerises", "Mozzarella", "Olives", "Pesto"], ["Cuire et refroidir les pâtes.", "Ajouter les légumes et la mozzarella.", "Mélanger avec le pesto."], ["salade", "été"], 15, 10, 4],
  ["croque-monsieur-001", "Croque-monsieur au four", "Un classique rapide et fondant.", ["8 tranches de pain", "Jambon", "Fromage", "Béchamel"], ["Garnir les tranches de pain.", "Couvrir de béchamel et fromage.", "Gratiner 15 minutes à 200 °C."], ["rapide", "famille"], 10, 15, 4],
  ["poelee-legumes-001", "Poêlée de légumes de saison", "Un accompagnement coloré et simple.", ["Courgettes", "Poivrons", "Carottes", "Oignon", "Herbes"], ["Couper les légumes.", "Les faire sauter dans l'huile.", "Cuire jusqu'à ce qu'ils soient tendres et assaisonner."], ["végétarien", "accompagnement"], 15, 20, 4],
  ["riz-cantonais-001", "Riz cantonais", "Un riz complet et rapide à préparer.", ["300 g de riz cuit", "2 œufs", "Petits pois", "Carotte", "Sauce soja"], ["Faire revenir les légumes.", "Ajouter le riz.", "Pousser le riz et cuire les œufs.", "Mélanger avec la sauce soja."], ["rapide", "asiatique"], 15, 15, 4],
  ["nouilles-legumes-001", "Nouilles sautées aux légumes", "Des nouilles colorées aux saveurs asiatiques.", ["250 g de nouilles", "Carotte", "Poivron", "Chou", "Sauce soja"], ["Cuire les nouilles.", "Faire sauter les légumes.", "Ajouter les nouilles et la sauce soja."], ["rapide", "asiatique"], 15, 15, 4],
  ["tacos-poulet-001", "Tacos de poulet", "Des tacos frais et conviviaux.", ["8 tortillas", "400 g de poulet", "Avocat", "Tomate", "Yaourt"], ["Cuire le poulet épicé.", "Préparer les garnitures.", "Garnir les tortillas et servir."], ["famille", "convivial"], 20, 20, 4],
  ["fajitas-legumes-001", "Fajitas aux légumes", "Des fajitas végétariennes pleines de couleurs.", ["8 tortillas", "Poivrons", "Oignon", "Haricots rouges", "Avocat"], ["Faire revenir les légumes.", "Ajouter les haricots.", "Garnir les tortillas et servir avec l'avocat."], ["végétarien", "convivial"], 15, 20, 4],
  ["salade-nicoise-001", "Salade niçoise", "Une salade complète et ensoleillée.", ["Salade verte", "Tomates", "Œufs", "Thon", "Haricots verts", "Olives"], ["Cuire les œufs et les haricots.", "Préparer les légumes.", "Assembler et assaisonner."], ["salade", "été"], 20, 10, 4],
  ["tian-legumes-001", "Tian de légumes", "Des légumes rôtis doucement au four.", ["Courgettes", "Aubergines", "Tomates", "Oignon", "Herbes de Provence"], ["Trancher les légumes.", "Les disposer dans un plat.", "Arroser d'huile et cuire 1 heure à 180 °C."], ["végétarien", "four"], 20, 60, 6],
  ["muffins-myrtilles-001", "Muffins aux myrtilles", "Des muffins moelleux pour le goûter.", ["250 g de farine", "2 œufs", "100 g de sucre", "150 ml de lait", "Myrtilles"], ["Mélanger les ingrédients secs.", "Ajouter les liquides.", "Incorporer les myrtilles.", "Cuire 25 minutes à 180 °C."], ["dessert", "goûter"], 15, 25, 10],
  ["galette-frangipane-001", "Galette frangipane", "Une galette dorée et fondante.", ["2 pâtes feuilletées", "100 g de poudre d'amande", "80 g de beurre", "2 œufs", "80 g de sucre"], ["Préparer la frangipane.", "Étaler sur une pâte et couvrir.", "Dorer et cuire 35 minutes à 180 °C."], ["dessert", "fête"], 25, 35, 8],
].map(([id, title, description, ingredients, steps, tags, prepTimeMinutes, cookTimeMinutes, servings]) => ({
  id: id as string,
  title: title as string,
  description: description as string,
  ingredients: JSON.stringify(ingredients),
  steps: JSON.stringify(steps),
  tags: JSON.stringify(tags),
  prepTimeMinutes: prepTimeMinutes as number,
  cookTimeMinutes: cookTimeMinutes as number,
  servings: servings as number,
  sourceType: "seed",
}));

async function main() {
  for (const recipe of recipes) {
    await prisma.recipe.upsert({ where: { id: recipe.id }, create: recipe, update: recipe });
  }
  console.log(`Seeded ${recipes.length} recipes without duplicates.`);
}

main().finally(() => prisma.$disconnect());
